title: caikitlearn.github.io

default_theme: dark
available_themes:
  - name: "dark"
    description: "My default dark theme."
  - name: "light"
    description: "My default light theme."
  - name: "jazz"
    description: "Solo cup design from the 90s."
  - name: "outrun"
    description: "For documentation sites."
  - name: "raptors"
    description: "90s retro Toronto Raptors."
  - name: "severance"
    description: "Keyboard from Severance (2022)."
  - name: "tyranitar"
    description: "Tyranitar."